// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkptMfBdP-yD51EBG_iQwZi3G4BVWchYk',
    appId: '1:212906666067:web:16beadc93879cdc420fea6',
    messagingSenderId: '212906666067',
    projectId: 'project-jordan-543dd',
    authDomain: 'project-jordan-543dd.firebaseapp.com',
    storageBucket: 'project-jordan-543dd.appspot.com',
    measurementId: 'G-9G91BW0X1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3L1g1TtwfNQmk3QGN9ddR_DHurI9uItM',
    appId: '1:212906666067:android:e22c7b61a24a925620fea6',
    messagingSenderId: '212906666067',
    projectId: 'project-jordan-543dd',
    storageBucket: 'project-jordan-543dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJY2R296Z62cglgKaOZ4PMzhouFV5Stw4',
    appId: '1:212906666067:ios:66e5ce8cea90d55020fea6',
    messagingSenderId: '212906666067',
    projectId: 'project-jordan-543dd',
    storageBucket: 'project-jordan-543dd.appspot.com',
    iosClientId: '212906666067-8ckei96t5gnggqt0u2354eb3eikmdh4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectJordan',
  );
}
